' Equates for building resource information

%THINBASIC_STRINGBUILDER_VERSIONMAJOR     = 1
%THINBASIC_STRINGBUILDER_VERSIONMINOR     = 9
%THINBASIC_STRINGBUILDER_VERSIONBUILD     = 16
%THINBASIC_STRINGBUILDER_VERSIONREVISION  = 17

$THIN_COMMON_COMPANYNAME                  = "Petr Schreiber"                         
$THINBASIC_STRINGBUILDER_FILEDESCRIPTION  = "StringBuilder module for thinBASIC"     
$THINBASIC_STRINGBUILDER_VERSIONLITERAL   = "1.9.16.17"                               
$THINBASIC_STRINGBUILDER_INTERNALNAME     = "StringBuilder"                          
$THINBASIC_STRINGBUILDER_ORIGINALFILENAME = "ThinBASIC_StringBuilder.dll"            
$THIN_COMMON_LEGALCOPYRIGHT               = "Copyright (c) Petr Schreiber 2016"        
$THINBASIC_STRINGBUILDER_PRODUCTNAME      = "StringBuilder"                          
$THIN_COMMON_COMMENT                      = "Support site: http://www.thinbasic.com/"                               
                                                                                         
